//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportComplexNaumov.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesComplex : DbContext
    {
        private static EntitiesComplex _context;
        public static EntitiesComplex GetContext()
        {
            if (_context == null)
                _context = new EntitiesComplex();
            return _context;
        }
        public EntitiesComplex()
            : base("name=EntitiesComplex")
        {
        }

    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonement> Abonement { get; set; }
        public virtual DbSet<Cekcia> Cekcia { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Instryctor> Instryctor { get; set; }
        public virtual DbSet<Section> Section { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trenirovki> Trenirovki { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
